1. Import NumPy

In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.0.2


2. Create a 1D Array

In [2]:
array_1d = np.array([10, 20, 30, 40, 50])

print("1D Array:")
print(array_1d)

1D Array:
[10 20 30 40 50]


3. Create a 2D Array

In [3]:
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("2D Array:")
print(array_2d)

2D Array:
[[1 2 3]
 [4 5 6]]


4. Create a 3D Array

In [4]:
array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("3D Array:")
print(array_3d)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


5. Check Array Dimensions

In [5]:
print("1D Array Dimensions:", array_1d.ndim)
print("2D Array Dimensions:", array_2d.ndim)
print("3D Array Dimensions:", array_3d.ndim)

1D Array Dimensions: 1
2D Array Dimensions: 2
3D Array Dimensions: 3


6. Check Array Shape

In [6]:
print("1D Shape:", array_1d.shape)
print("2D Shape:", array_2d.shape)
print("3D Shape:", array_3d.shape)

1D Shape: (5,)
2D Shape: (2, 3)
3D Shape: (2, 2, 2)


7. Check Array Data Type

In [7]:
print("1D Data Type:", array_1d.dtype)
print("2D Data Type:", array_2d.dtype)
print("3D Data Type:", array_3d.dtype)

1D Data Type: int64
2D Data Type: int64
3D Data Type: int64


8. Check Number of Elements

In [8]:
print("1D Size:", array_1d.size)
print("2D Size:", array_2d.size)
print("3D Size:", array_3d.size)

1D Size: 5
2D Size: 6
3D Size: 8


9. Indexing 1D Array

In [9]:
array = np.array([10, 20, 30, 40, 50])

print("First element:", array[0])
print("Third element:", array[2])
print("Last element:", array[-1])

First element: 10
Third element: 30
Last element: 50


10. Indexing 2D Array

In [10]:
array = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("First row, first column:", array[0, 0])
print("First row, third column:", array[0, 2])
print("Second row, second column:", array[1, 1])

First row, first column: 10
First row, third column: 30
Second row, second column: 50


11. Indexing 3D Array

In [11]:
array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Element:", array[0, 0, 0])
print("Element:", array[1, 1, 1])

Element: 1
Element: 8


12. Slicing a 1D Array

In [12]:
array = np.array([10, 20, 30, 40, 50])

print("Elements from index 1 to 3:")
print(array[1:4])

Elements from index 1 to 3:
[20 30 40]


13. Slicing with Step

In [13]:
array = np.array([10, 20, 30, 40, 50])

print("Every second element:")
print(array[::2])

Every second element:
[10 30 50]


14. Slicing a 2D Array

In [14]:
array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("First two rows and first two columns:")
print(array[0:2, 0:2])

First two rows and first two columns:
[[1 2]
 [4 5]]


15. Reshaping an Array

In [15]:
array = np.arange(1, 13)

print("Original Array:")
print(array)

reshaped_array = array.reshape(3, 4)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


16. Reshape into 2 × 6

In [16]:
array = np.arange(1, 13)

reshaped_array = array.reshape(2, 6)

print(reshaped_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


17. zeros()

In [17]:
zeros_array = np.zeros((3, 4))

print("Array of zeros:")
print(zeros_array)

Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


18. ones()

In [18]:
ones_array = np.ones((3, 4))

print("Array of ones:")
print(ones_array)

Array of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


19. arange()

In [19]:
array = np.arange(1, 11)

print(array)

[ 1  2  3  4  5  6  7  8  9 10]


20. arange() with Step

In [20]:
array = np.arange(0, 20, 2)

print(array)

[ 0  2  4  6  8 10 12 14 16 18]


21. linspace()

In [21]:
array = np.linspace(0, 10, 5)

print(array)

[ 0.   2.5  5.   7.5 10. ]


22. Mathematical Operations

In [22]:
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


23. Power and Square Root

In [23]:
array = np.array([4, 9, 16, 25])

print("Square:", array ** 2)
print("Square Root:", np.sqrt(array))

Square: [ 16  81 256 625]
Square Root: [2. 3. 4. 5.]


24. Vectorized Operations

In [24]:
marks = np.array([50, 60, 70, 80, 90])

updated_marks = marks + 5

print("Original Marks:")
print(marks)

print("\nUpdated Marks:")
print(updated_marks)

Original Marks:
[50 60 70 80 90]

Updated Marks:
[55 65 75 85 95]


25. Vectorized Multiplication

In [25]:
prices = np.array([100, 200, 300, 400])

new_prices = prices * 0.9

print("Original Prices:", prices)
print("After 10% Discount:", new_prices)

Original Prices: [100 200 300 400]
After 10% Discount: [ 90. 180. 270. 360.]


26. Boolean Masking

In [26]:
marks = np.array([45, 67, 82, 91, 38, 76, 55])

result = marks[marks >= 50]

print("Marks greater than or equal to 50:")
print(result)

Marks greater than or equal to 50:
[67 82 91 76 55]


27. Boolean Masking for High Scores

In [27]:
marks = np.array([45, 67, 82, 91, 38, 76, 55])

high_scores = marks[marks >= 80]

print("High Scores:")
print(high_scores)

High Scores:
[82 91]


28. Boolean Masking with Two Conditions

In [28]:
marks = np.array([45, 67, 82, 91, 38, 76, 55])

result = marks[(marks >= 50) & (marks <= 80)]

print("Marks between 50 and 80:")
print(result)

Marks between 50 and 80:
[67 76 55]


29. Broadcasting

In [29]:
array = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

result = array + 5

print("Original Array:")
print(array)

print("\nAfter adding 5:")
print(result)

Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

After adding 5:
[[15 25 35]
 [45 55 65]
 [75 85 95]]


30. Broadcasting with Another Array

In [30]:
array = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

values = np.array([1, 2, 3])

result = array + values

print("Result:")
print(result)

Result:
[[11 22 33]
 [41 52 63]
 [71 82 93]]


31. sum()

In [31]:
array = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(array))

Sum: 150


32. mean()

In [32]:
array = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(array))

Mean: 30.0


33. min()

In [33]:
array = np.array([10, 20, 30, 40, 50])

print("Minimum:", np.min(array))

Minimum: 10


34. max()

In [34]:
array = np.array([10, 20, 30, 40, 50])

print("Maximum:", np.max(array))

Maximum: 50


35. median()

In [35]:
array = np.array([10, 20, 30, 40, 50])

print("Median:", np.median(array))

Median: 30.0


36. All Aggregate Functions Together

In [36]:
array = np.array([10, 20, 30, 40, 50])

print("Array:", array)
print("Sum:", np.sum(array))
print("Mean:", np.mean(array))
print("Minimum:", np.min(array))
print("Maximum:", np.max(array))
print("Median:", np.median(array))

Array: [10 20 30 40 50]
Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Median: 30.0


37. Aggregate Functions on 2D Array

In [37]:
scores = np.array([
    [80, 75, 90],
    [65, 88, 72],
    [95, 91, 89]
])

print("Scores:")
print(scores)

print("\nTotal:", np.sum(scores))
print("Mean:", np.mean(scores))
print("Minimum:", np.min(scores))
print("Maximum:", np.max(scores))
print("Median:", np.median(scores))

Scores:
[[80 75 90]
 [65 88 72]
 [95 91 89]]

Total: 745
Mean: 82.77777777777777
Minimum: 65
Maximum: 95
Median: 88.0


38. Row-wise Sum

In [38]:
scores = np.array([
    [80, 75, 90],
    [65, 88, 72],
    [95, 91, 89]
])

row_sum = np.sum(scores, axis=1)

print("Row-wise Sum:")
print(row_sum)

Row-wise Sum:
[245 225 275]


39. Column-wise Sum

In [39]:
scores = np.array([
    [80, 75, 90],
    [65, 88, 72],
    [95, 91, 89]
])

column_sum = np.sum(scores, axis=0)

print("Column-wise Sum:")
print(column_sum)

Column-wise Sum:
[240 254 251]


40. Complete Numerical Data Analysis Example

In [40]:
student_marks = np.array([
    72, 85, 64, 91, 78,
    88, 55, 93, 69, 81
])

print("Student Marks:")
print(student_marks)

print("\n----- Statistical Analysis -----")

print("Total Marks:", np.sum(student_marks))
print("Average Marks:", np.mean(student_marks))
print("Highest Marks:", np.max(student_marks))
print("Lowest Marks:", np.min(student_marks))
print("Median Marks:", np.median(student_marks))

high_scores = student_marks[student_marks >= 80]

print("\nStudents scoring 80 or above:")
print(high_scores)

print(
    "Number of students scoring 80 or above:",
    np.sum(student_marks >= 80)
)

Student Marks:
[72 85 64 91 78 88 55 93 69 81]

----- Statistical Analysis -----
Total Marks: 776
Average Marks: 77.6
Highest Marks: 93
Lowest Marks: 55
Median Marks: 79.5

Students scoring 80 or above:
[85 91 88 93 81]
Number of students scoring 80 or above: 5
